kind: Deployment
apiVersion: apps/v1

metadata:
  name: assets

spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: assets
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: assets
    spec:
      containers:
      - name: assets
        image: ghcr.io/gw2treasures/gw2treasures.com/assets:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "20m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            port: 80
            path: "/gw2treasures/assets/css/gw2t.css"
          initialDelaySeconds: 30
          timeoutSeconds: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
