version: '3'

services:
  legacy-importer:
    image: gw2treasures/legacy-importer
    build: apps/legacy-importer
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://gw2treasures:gw2treasures@next-db:5432/gw2treasures?schema=public
      - LEGACY_DATABASE_URL=mysql://gw2treasures:3c09b766-101c-4500-9f25-33450753e88a@db:3306/gw2treasures
    networks:
      - default
      - gw2treasures_legacy

networks:
  default:
  gw2treasures_legacy:
    external: true
    name: gw2treasures_legacy
