version: '3'

services:
  database-old:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gw2treasures
      - POSTGRES_PASSWORD=gw2treasures
      - POSTGRES_DB=gw2treasures
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .docker/database:/var/lib/postgresql/data
