version: '3'

services:
  web:
    image: gw2treasures/web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://gw2treasures:gw2treasures@database:5432/gw2treasures?schema=public
      - GW2T_NEXT_DOMAIN=gw2treasures.localhost
      - FORCE_COLOR=1
    ports:
      - 3000:3000

  worker:
    image: gw2treasures/worker
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    restart: unless-stopped
    depends_on:
      - database
      - database-migration
    environment:
      - DATABASE_URL=postgresql://gw2treasures:gw2treasures@database:5432/gw2treasures?schema=public
    deploy:
      replicas: 2

  database:
    image: timescale/timescaledb:2.14.0-pg16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gw2treasures
      - POSTGRES_PASSWORD=gw2treasures
      - POSTGRES_DB=gw2treasures
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .docker/database-pg16:/var/lib/postgresql/data
    ports:
      - 54326:5432

  database-migration:
    image: gw2treasures/database-migration
    build:
      context: .
      dockerfile: apps/database-migration/Dockerfile
    restart: on-failure
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://gw2treasures:gw2treasures@database:5432/gw2treasures?schema=public
