version: '3'

services:
  next:
    image: gw2treasures/next
    build: apps/next
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://gw2treasures:gw2treasures@next-db:5432/gw2treasures?schema=public
      - GW2T_NEXT_DOMAIN=next.gw2treasures.localhost
      - FORCE_COLOR=1
    ports:
      - 3000:3000

  worker:
    image: gw2treasures/worker
    build: apps/worker
    restart: unless-stopped
    depends_on:
      - next-db
    environment:
      - DATABASE_URL=postgresql://gw2treasures:gw2treasures@next-db:5432/gw2treasures?schema=public
    deploy:
      replicas: 2

  next-db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gw2treasures
      - POSTGRES_PASSWORD=gw2treasures
      - POSTGRES_DB=gw2treasures
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .docker/next-db:/var/lib/postgresql/data
    ports:
      - 54326:5432
