version: '3'

services:
  web:
    image: gw2treasures/web
    build:
      context: web
      dockerfile: docker/Dockerfile
    environment:
      - GW2T_URL=http://gw2treasures.localhost/
      - GW2T_DOMAIN=gw2treasures.localhost
      - GW2T_TRANSLATE_PASSWORD=translate
      - GW2T_DB_HOST=db
      - GW2T_DB_USER=gw2treasures
      - GW2T_DB_PASS=3c09b766-101c-4500-9f25-33450753e88a
      - GW2T_DB_NAME=gw2treasures
      - GW2T_EVENT=
      - GW2T_TRACKING_CODE=
      - GW2T_ASSETS=http://assets.gw2treasures-cdn.localhost
    restart: unless-stopped
  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=gw2treasures
      - MYSQL_USER=gw2treasures
      - MYSQL_PASSWORD=3c09b766-101c-4500-9f25-33450753e88a
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - gw2treasures-db:/var/lib/mysql
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOSTS=db
      - UPLOAD_LIMIT=64M
    depends_on:
      - db
  reverse-proxy:
    image: gw2treasures/reverse-proxy
    build: reverse-proxy
    environment:
      - GW2T_DOMAIN=gw2treasures.localhost
      - GW2T_APP=http://web
      - GW2T_ASSET_DOMAIN=assets.gw2treasures-cdn.localhost
      - GW2T_ASSETS=http://assets
      - GW2T_PMA=http://phpmyadmin
      - GW2T_STORAGE_DOMAIN=storage.gw2treasures.localhost
      - GW2T_STORAGE=http://storage
    depends_on:
      - web
      - assets
      - phpmyadmin
      - storage
    ports: 
      - 80:80
  assets:
    image: gw2treasures/assets
    build: assets
    restart: unless-stopped
  storage:
    image: gw2treasures/storage
    build: storage
    restart: unless-stopped

volumes: 
  gw2treasures-db:
