services:
  database-old:
    image: timescale/timescaledb:2.16.1-pg16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gw2treasures
      - POSTGRES_PASSWORD=gw2treasures
      - POSTGRES_DB=gw2treasures
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .docker/database-pg16:/var/lib/postgresql/data
