apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gw2treasures-legacy

commonLabels:
  app.kubernetes.io/part-of: gw2treasures-legacy

resources:
- namespace.yaml
- assets
- cache
- db
- storage
- web
- wvw-crawler
