name: Pull Docker Images
description: Composite task to pull docker images

inputs:
  platform:
    description: The platform (amd64/arm64)
    required: false
    default: '*'
  target:
    description: The target image to use (web/...)
    required: false
    default: '*'

outputs:
  digests:
    description: Digests of the loaded images
    value: ${{ steps.digests.outputs.digests }}

runs:
  using: composite
  steps:
  - name: Download images
    uses: actions/download-artifact@v4
    with:
      path: /tmp/images
      pattern: docker-image-${{ inputs.target }}-${{ inputs.platform }}
      merge-multiple: true
  - name: Load images
    shell: bash
    run: ls /tmp/images/image-*.tar | xargs -L1 docker image load --input
  - name: Docker images
    shell: bash
    run: docker images --digests
  - name: Output digests
    id: digests
    shell: bash
    run: |
      DIGESTS=$(echo $(cat /tmp/images/image-*.sha256))
      echo "digests=$DIGESTS"
      echo "digests=$DIGESTS" >> $GITHUB_OUTPUT
