apiVersion: batch/v1
kind: Job

metadata:
  name: database-migration

spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      tolerations:
      - key: arch
        operator: Equal
        value: arm64
        effect: NoSchedule
      containers:
      - name: database-migration
        image: ghcr.io/gw2treasures/gw2treasures.com/database-migration:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: next
              key: db
      restartPolicy: Never
