kind: Deployment
apiVersion: apps/v1

metadata:
  name: storage

spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: storage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: storage
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: storage
        image: ghcr.io/gw2treasures/gw2treasures.com/legacy/storage:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "20m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: SELF
          valueFrom:
            configMapKeyRef:
              name: storage
              key: self
        - name: TRUSTED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: storage
              key: trusted_origins
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            port: 80
            path: "/storage.html"
          initialDelaySeconds: 30
          timeoutSeconds: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
