apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gw2treasures-legacy

commonLabels:
  app.kubernetes.io/part-of: gw2treasures-legacy


resources:
- ../base
- assets
- db
- storage
- web
- phpmyadmin

images:
- name: ghcr.io/gw2treasures/gw2treasures.com/legacy/assets
  newTag: latest
- name: ghcr.io/gw2treasures/gw2treasures.com/legacy/reverse-proxy
  newTag: latest
- name: ghcr.io/gw2treasures/gw2treasures.com/legacy/storage
  newTag: latest
- name: ghcr.io/gw2treasures/gw2treasures.com/legacy/web
  newTag: latest
- name: ghcr.io/gw2treasures/gw2treasures.com/legacy/wvw-crawler
  newTag: latest
