apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gw2treasures

commonLabels:
  app.kubernetes.io/part-of: gw2treasures

resources:
- ../base
- next
- next-db
- next-importer

images:
- name: ghcr.io/gw2treasures/gw2treasures.com/web
  newTag: latest
  newName: gw2treasures/web
  
- name: ghcr.io/gw2treasures/gw2treasures.com/legacy-importer
  newTag: latest
  newName: gw2treasures/legacy-importer

- name: ghcr.io/gw2treasures/gw2treasures.com/worker
  newTag: latest
  newName: gw2treasures/worker

- name: ghcr.io/gw2treasures/gw2treasures.com/database-migration
  newTag: latest
  newName: gw2treasures/database-migration
