apiVersion: batch/v1
kind: Job

metadata:
  name: next-importer

spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: next-importer
        image: ghcr.io/gw2treasures/gw2treasures.com/legacy-importer:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: next
              key: db
        - name: LEGACY_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: next-importer
              key: legacy_db
      restartPolicy: Never
