apiVersion: apps/v1
kind: Deployment

metadata:
  name: database-pg17

spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: database-pg17
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: database-pg17
    spec:
      tolerations:
      - key: arch
        operator: Equal
        value: arm64
        effect: NoSchedule
      volumes:
      - name: database-pg17-data
        persistentVolumeClaim:
          claimName: database-pg17
      # increase shared memory (/dev/shm) (see https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614)
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: database-pg17
        image: timescale/timescaledb:2.21.2-pg17
        args:
        - "postgres"
        - "-c"
        - "max_connections=80"
        resources:
          requests:
            memory: "3072Mi"
            cpu: "250m"
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: database-pg17
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: database-pg17
              key: password
        - name: POSTGRES_DB
          value: gw2treasures
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -i
              - -c
              - psql -U $POSTGRES_USER -d $POSTGRES_DB -c SELECT 1
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -i
              - -c
              - psql -U $POSTGRES_USER -d $POSTGRES_DB -c SELECT 1
          initialDelaySeconds: 45
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: database-pg17-data
          mountPath: /var/lib/postgresql/data
        - name: dshm
          mountPath: /dev/shm
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
