apiVersion: apps/v1
kind: Deployment

metadata:
  name: database-pg16

spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: database-pg16
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: database-pg16
    spec:
      tolerations:
      - key: arch
        operator: Equal
        value: arm64
        effect: NoSchedule
      volumes:
      - name: database-pg16-data
        persistentVolumeClaim:
          claimName: database-pg16
      containers:
      - name: database-pg16
        image: timescale/timescaledb:2.15.3-pg16
        args:
        - "postgres"
        - "-c"
        - "max_connections=50"
        resources:
          requests:
            memory: "1536Mi"
            cpu: "100m"
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: database-pg16
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: database-pg16
              key: password
        - name: POSTGRES_DB
          value: gw2treasures
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

        readinessProbe:
          exec:
            command: 
              - /bin/sh
              - -i
              - -c
              - psql -U $POSTGRES_USER -d $POSTGRES_DB -c SELECT 1
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -i
              - -c
              - psql -U $POSTGRES_USER -d $POSTGRES_DB -c SELECT 1
          initialDelaySeconds: 45
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: database-pg16-data
          mountPath: /var/lib/postgresql/data
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
