apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gw2treasures

commonLabels:
  app.kubernetes.io/part-of: gw2treasures

resources:
- ../base
- next
- next-db
- next-importer

images:
# - name: ghcr.io/gw2treasures/gw2treasures.com/next
#   newTag: local
#   newName: gw2treasures/next

# - name: ghcr.io/gw2treasures/gw2treasures.com/next-importer
#   newTag: local
#   newName: gw2treasures/next-importer

# - name: ghcr.io/gw2treasures/gw2treasures.com/next-worker
#   newTag: local
#   newName: gw2treasures/next-worker
