kind: Deployment
apiVersion: apps/v1

metadata:
  name: next

spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: next
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: next
    spec:
      tolerations:
      - key: arch
        operator: Equal
        value: arm64
        effect: NoSchedule
      containers:
      - name: next
        image: ghcr.io/gw2treasures/gw2treasures.com/web:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: next
              key: db
        - name: GW2T_NEXT_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: next
              key: domain
        - name: GW2ME_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: next
              key: gw2me_client_id
              optional: true
        - name: GW2ME_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: next
              key: gw2me_client_secret
              optional: true
        - name: SIGNING_KEY
          valueFrom:
            configMapKeyRef:
              name: next
              key: signing_key
              optional: true
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 3000
            path: "/_/health"
          initialDelaySeconds: 3
          timeoutSeconds: 1
          failureThreshold: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            port: 3000
            path: "/_/health"
          initialDelaySeconds: 30
          timeoutSeconds: 1
          failureThreshold: 6
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30    
