kind: Deployment
apiVersion: apps/v1

metadata:
  name: next-worker

spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: next-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: next-worker
    spec:
      containers:
      - name: next-worker
        image: ghcr.io/gw2treasures/gw2treasures.com/next-worker:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: next
              key: db
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30    
