kind: ConfigMap
apiVersion: v1

metadata:
  name: next

data:
  db: postgresql://gw2treasures:f51f6aa0-73a7-45de-a068-6867fec97dc2@next-db:5432/gw2treasures?schema=public
  domain: next.gw2treasures.kubernetes.localhost
