apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
          - name: cron
            image: ghcr.io/gw2treasures/gw2treasures.com/legacy/web:latest
            command: 
            - /bin/sh
            - cron.sh
            resources:
              requests:
                memory: "128Mi"
                cpu: "50m"
              limits:
                memory: "512Mi"
                cpu: "250m"
            ports:
            - containerPort: 80
              protocol: TCP
            env:
            - name: GW2T_ENV
              valueFrom:
                configMapKeyRef:
                  name: web
                  key: env
            - name: GW2T_URL
              valueFrom:
                configMapKeyRef:
                  name: web
                  key: url
            - name: GW2T_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: web
                  key: domain
            - name: GW2T_TRANSLATE_PASSWORD
              value: translate
            - name: GW2T_DB_HOST
              value: db
            - name: GW2T_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: user
            - name: GW2T_DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: db
                  key: password
            - name: GW2T_DB_NAME
              value: gw2treasures
            - name: GW2T_EVENT
              valueFrom:
                configMapKeyRef:
                  name: web
                  key: event
            - name: GW2T_TRACKING_CODE
              valueFrom:
                configMapKeyRef:
                  name: web
                  key: tracking_code
            - name: GW2T_ASSETS
              valueFrom:
                configMapKeyRef:
                  name: web
                  key: assets
            - name: GW2T_STORAGE
              valueFrom:
                configMapKeyRef:
                  name: web
                  key: storage
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: web
                  key: sentry
            - name: TRUSTED_PROXY
              valueFrom:
                configMapKeyRef:
                  name: web
                  key: trustedProxy
                  optional: true
          restartPolicy: OnFailure
