version: '3'

services:
  web:
    image: gw2treasures/legacy/web
    build:
      context: web
      dockerfile: docker/Dockerfile
    environment:
      - GW2T_ENV=dev
      - GW2T_URL=http://gw2treasures.localhost/
      - GW2T_DOMAIN=gw2treasures.localhost
      - GW2T_TRANSLATE_PASSWORD=translate
      - GW2T_DB_HOST=db
      - GW2T_DB_USER=gw2treasures
      - GW2T_DB_PASS=3c09b766-101c-4500-9f25-33450753e88a
      - GW2T_DB_NAME=gw2treasures
      - GW2T_EVENT=
      - GW2T_TRACKING_CODE=
      - GW2T_ASSETS=http://assets.gw2treasures-cdn.localhost
      - GW2T_STORAGE=http://storage.gw2treasures.localhost
      - SENTRY_DSN=
    restart: unless-stopped
    networks:
      - legacy
  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=gw2treasures
      - MYSQL_USER=gw2treasures
      - MYSQL_PASSWORD=3c09b766-101c-4500-9f25-33450753e88a
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - gw2treasures-db:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - legacy
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOSTS=db
      - UPLOAD_LIMIT=64M
    depends_on:
      - db
    networks:
      - legacy
  cache:
    image: redis:alpine
    restart: unless-stopped
    command: >
      redis-server
      --save ""
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
    networks:
      - legacy
  reverse-proxy:
    image: gw2treasures/legacy/reverse-proxy
    build: reverse-proxy
    restart: unless-stopped
    environment:
      - GW2T_DOMAIN=gw2treasures.localhost
      - GW2T_APP=http://web
      - GW2T_ASSET_DOMAIN=assets.gw2treasures-cdn.localhost
      - GW2T_ASSETS=http://assets
      - GW2T_PMA=http://phpmyadmin
      - GW2T_STORAGE_DOMAIN=storage.gw2treasures.localhost
      - GW2T_STORAGE=http://storage
    depends_on:
      - web
      - assets
      - phpmyadmin
      - storage
    ports:
      - 80:80
    networks:
      - legacy
  assets:
    image: gw2treasures/legacy/assets
    build: assets
    restart: unless-stopped
    networks:
      - legacy
  storage:
    image: gw2treasures/legacy/storage
    build: storage
    restart: unless-stopped
    environment:
      - SELF=http://storage.gw2treasures.localhost
      - TRUSTED_ORIGINS=http://de.gw2treasures.localhost,http://en.gw2treasures.localhost,http://es.gw2treasures.localhost,http://fr.gw2treasures.localhost,http://dev.gw2treasures.localhost
    networks:
      - legacy
  wvw-crawler:
    image: gw2treasures/legacy/wvw-crawler
    build: wvw-crawler
    restart: unless-stopped
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=gw2treasures
      - MYSQL_USER=gw2treasures
      - MYSQL_PASSWORD=3c09b766-101c-4500-9f25-33450753e88a
    depends_on:
      - db
    networks:
      - legacy

volumes:
  gw2treasures-db:

networks:
  legacy:
    name: gw2treasures_legacy
    external: true
