kind: Deployment
apiVersion: apps/v1

metadata:
  name: next-worker

spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: next-worker
  template:
    metadata:
      labels:
        name: next-worker
    spec:
      containers:
      - name: next-worker
        image: ghcr.io/gw2treasures/gw2treasures.com/worker:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: next
              key: db
        - name: HEALTH_PORT
          value: "9090"
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 9090
          initialDelaySeconds: 3
          timeoutSeconds: 15
          failureThreshold: 5
          periodSeconds: 60
        livenessProbe:
          httpGet:
            port: 9090
          initialDelaySeconds: 3
          timeoutSeconds: 15
          failureThreshold: 6
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30    
