name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  # renovate: datasource=npm packageName=npm
  NPM_VERSION: 10.9.0
  # renovate: datasource=npm packageName=renovate
  RENOVATE_VERSION: 38.128.7

  # renovate: datasource=node-version packageName=node
  NODE_18_VERSION: 18.20.4
  # renovate: datasource=node-version packageName=node
  NODE_20_VERSION: 20.18.0
  # renovate: datasource=node-version packageName=node
  NODE_22_VERSION: 22.10.0


jobs:
  build-node:
    name: Build / Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20, 22 ]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env[format('NODE_{0}_VERSION', matrix.node)] }}
        cache: npm
    - name: Install latest npm
      run: |
        npm install --global npm@${{ env.NPM_VERSION }}
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Cache turbo
      uses: actions/cache@v4
      with:
        path: ./.turbo/cache
        key: turbo2-cache-build-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo2-cache-build-${{ runner.os }}-
    - name: Run Build
      run: npm run build
      env:
        SKIP_LINT: true

  docker:
    name: Docker (${{ matrix.platform }})
    strategy:
      matrix:
        platform: [ amd64, arm64 ]
    uses: ./.github/workflows/docker-build-and-test.yml
    with:
      platform: ${{ matrix.platform }}

  test-unit:
    name: Test / Unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Install latest npm
      run: |
        npm install --global npm@${{ env.NPM_VERSION }}
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Cache turbo
      uses: actions/cache@v4
      with:
        path: ./.turbo/cache
        key: turbo2-cache-test-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo2-cache-test-${{ runner.os }}-
    - name: Run Test
      run: npm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Install latest npm
      run: |
        npm install --global npm@${{ env.NPM_VERSION }}
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Cache turbo
      uses: actions/cache@v4
      with:
        path: ./.turbo/cache
        key: turbo2-cache-lint-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo2-cache-lint-${{ runner.os }}-
    - name: Run Lint
      run: npm run lint

  renovate:
    name: Validate renovate config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install renovate
      run: npm i -g renovate@${{ env.RENOVATE_VERSION }}
    - name: Validate config
      run: renovate-config-validator --strict

  success:
    name: Success
    needs: [docker, test-unit, build-node, lint, renovate]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Check job status
      run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Success
      run: exit 0

  publish-docker:
    name: Publish (docker)
    if: github.event_name != 'merge_group'
    needs: [success]
    uses: ./.github/workflows/publish-docker.yml

  publish-npm:
    name: Publish (npm)
    if: github.event_name != 'merge_group'
    needs: [success]
    uses: ./.github/workflows/publish-npm.yml
