name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}


jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-node.yml

  docker:
    name: Docker (${{ matrix.platform }})
    strategy:
      matrix:
        platform: [ amd64 ]
    uses: ./.github/workflows/docker-build-and-test.yml
    with:
      platform: ${{ matrix.platform }}

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  renovate:
    name: Renovate
    uses: ./.github/workflows/renovate-validate-config.yml

  prisma:
    name: Prisma
    uses: ./.github/workflows/prisma-pending-migrations.yml

  success:
    name: Success
    needs: [build, docker, test, lint, renovate]
    runs-on: ubuntu-24.04
    if: always()
    steps:
    - name: Check job status
      run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Success
      run: exit 0

  publish-docker:
    name: Publish (docker)
    if: github.event_name != 'merge_group'
    needs: [success]
    uses: ./.github/workflows/publish-docker.yml

  publish-npm:
    name: Publish (npm)
    if: github.event_name != 'merge_group'
    needs: [success]
    uses: ./.github/workflows/publish-npm.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
