name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  image:
    name: Build image ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ web, worker, legacy-importer, database-migration ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      uses: crazy-max/docker-bake-action@fix-bake-def
      with:
        files: |
          ./docker-compose.yml
          ./docker-compose.importer.yml
        targets: ${{ matrix.target }}
        set: |
          *.output=type=docker,dest=/tmp/image-${{ matrix.target }}.tar
          *.cache-from=type=gha,scope=build-${{ matrix.target }}
          *.cache-to=type=gha,scope=build-${{ matrix.target }},mode=max
    - uses: actions/upload-artifact@v3
      with:
        name: docker-image-${{ matrix.target }}
        path: /tmp/image-${{ matrix.target }}.tar

  compose-test:
    name: Test / docker compose
    runs-on: ubuntu-latest
    needs: image
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: /tmp
    - name: Load docker image
      run: ls /tmp/docker-image-*/image-*.tar | xargs -L1 docker load --input
    - name: Start docker compose
      run: docker compose up -d
    - name: Wait 30s
      run: sleep 30
    - run: docker compose ps -a
    - run: docker compose logs
    - name: Verify docker containers are running
      run: docker inspect --format "{{.ID}} {{.Name}} {{.State.Status}} {{.RestartCount}}" $(docker compose ps -aq) | node .github/actions/docker-compose-status.js
    - name: Stop docker compose
      run: docker compose down

  push:
    name: Push ${{ matrix.target }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [image, compose-test]
    strategy:
      matrix:
        target: [ web, worker, legacy-importer, database-migration ]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: docker-image-${{ matrix.target }}
        path: /tmp
    - name: Load docker image
      run: docker load --input /tmp/image-${{ matrix.target }}.tar
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image  
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}/${{ matrix.target }}
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag gw2treasures/${{ matrix.target }} $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
