name: Lint
on:
  workflow_call:


jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: true
    - name: Setup Node.js env
      uses: ./.github/actions/setup-node-env
      with:
        cache-key: lint
    - name: Run Lint
      run: pnpm run lint
