name: Pending prisma migrations
on:
  workflow_call:

jobs:
  pending-migrations:
    name: Pending Migrations
    runs-on: ubuntu-latest
    env:
      DB: postgresql://gw2treasures:gw2treasures@localhost:5432/gw2treasures
    services:
      database:
        image: timescale/timescaledb:2.17.2-pg17
        env:
          POSTGRES_USER: gw2treasures
          POSTGRES_PASSWORD: gw2treasures
          POSTGRES_DB: gw2treasures
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js env
      uses: ./.github/actions/setup-node-env
    - name: Setup database
      run: |
        psql "${{ env.DB }}" -c 'CREATE EXTENSION IF NOT EXISTS "timescaledb";'
        psql "${{ env.DB }}" -c 'ALTER EXTENSION "timescaledb" UPDATE;'
    - name: Run prisma diff
      run: |
        pnpm --filter @gw2treasures/database exec \
        prisma migrate diff \
          --exit-code \
          --from-schema-datamodel "./prisma/schema.prisma" \
          --to-migrations "./prisma/migrations" \
          --shadow-database-url "${{ env.DB }}?schema=public"
