name: Test
on:
  workflow_call:


jobs:
  unit:
    name: Unit
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: true
    - name: Setup Node.js env
      uses: ./.github/actions/setup-node-env
      with:
        cache-key: test
    - name: Setup playwright
      # install chromium including system dependencies and without headless shell (we use the real browser in headless mode)
      run: pnpm exec playwright install chromium --with-deps --no-shell
    - name: Run Test
      run: pnpm run test
